development:
  adapter: postgresql
  encoding: unicode
  database: srbuj_development
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: srbuj_production
  pool: 5
  username: root
  password:
